[project]
name = "cc"
version = "0.1"

[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["cc*", "src*", "test*"]
namespaces = true