translation_unit ::= declaration
declaration ::= type_specifier
type_specifier ::= VOID | CHAR | SHORT | INT | LONG | FLOAT | DOUBLE | SIGNED | UNSIGNED | struct_or_union_specifier 
struct_or_union_specifier ::= struct_or_union ID ID "{" struct_declaration_list "}"
struct_or_union ::= STRUCT | UNION
struct_declaration_list ::= struct_declaration | struct_declaration_list struct_declaration 
struct_declarator_list ::= struct_declarator | struct_declarator_list "," struct_declarator
struct_declaration ::= struct_declarator_list ";"
struct_declarator ::= declarator
declarator ::= direct_declarator
direct_declarator ::= ID | CONSTANT | direct_declarator "[" constant_expression "]" | direct_declarator "[" "]"
constant_expression ::= ID | CONSTANT

struct tname funcblk { NAME, 0 };