1: translation_unit ::= declaration

2: declaration ::= type_specifier

3: type_specifier ::= VOID | CHAR | SHORT | INT | LONG | FLOAT | DOUBLE | SIGNED | UNSIGNED | struct_or_union_specifier 

4: struct_or_union_specifier ::= struct_or_union ID ID "{" struct_declaration_list "}"

5: struct_or_union ::= STRUCT | UNION

6: struct_declaration_list ::= struct_declaration | struct_declaration_list struct_declaration 

7: struct_declarator_list ::= struct_declarator | struct_declarator_list "," struct_declarator

8: struct_declaration ::= struct_declarator_list ";"

9: struct_declarator ::= declarator

10: declarator ::= direct_declarator

11: direct_declarator ::= ID | CONSTANT | direct_declarator "[" constant_expression "]" | direct_declarator "[" "]"

12: constant_expression ::= ID | CONSTANT

